version: '3'
services:
  openecoe-webui:
    build:
      context: .
    image: openecoe/webui:latest
    container_name: openecoe-webui
    environment:
      DEBUG: "True"
      BACKEND_URL: "http://localhost:8081"
    ports:
      - 8082:80